//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use crate::features::users::model::{api_key, user};
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "site")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub url: String,
    pub url_list: String,
    pub path_link: Option<String>,
    pub path_title: Option<String>,
    pub path_content: Option<String>,
    pub path_image: Option<String>,
    pub path_video: Option<String>,
    pub path_remove: Option<String>,
    pub screenshot: Option<bool>,
    pub status: Option<bool>,
    pub user_id: i64,
    pub api_key_id: i64,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation, Serialize)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "user::Entity",
        from = "Column::UserId",
        to = "user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(
        belongs_to = "api_key::Entity",
        from = "Column::ApiKeyId",
        to = "api_key::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ApiKey,
}

impl Related<api_key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKey.def()
    }
}

impl Related<user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
